# -*- coding: utf-8 -*-
"""dashboard.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j1k4_K7an31mie67y96-VbSgDdSLi5JM
"""

pip install numpy pandas scipy matplotlib seaborn jupyter

!conda activate main-ds
!pip install streamlit babel

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt

# Load Data
all_data = pd.DataFrame({
    "Kategori": ["Minggu", "Senin", "Selasa", "Rabu", "Kamis", "Jumat", "Sabtu"] + [f"Jam {i}" for i in range(24)],
    "Jumlah Casual Users": [140521, 70784, 57843, 57319, 61460, 78238, 153852] + [7375, 4709, 3412, 2805, 2547, 2441, 4101, 9251, 20953, 27740, 31586, 36707, 37287, 37061, 33898, 31591, 31240, 26733, 21652, 15204, 11060, 8851, 7852, 6840]
})

# Pisahkan Data Harian dan Jam
casual_by_day = all_data[all_data["Kategori"].str.contains("Minggu|Senin|Selasa|Rabu|Kamis|Jumat|Sabtu")]
casual_by_day.set_index("Kategori", inplace=True)
casual_by_hour = all_data[all_data["Kategori"].str.contains("Jam")]
casual_by_hour["Jam"] = casual_by_hour["Kategori"].str.extract("(\\d+)").astype(int)
casual_by_hour.set_index("Jam", inplace=True)

# Streamlit Dashboard
st.title("Dashboard Pengguna Kasual")

# Pie Chart
st.subheader("Distribusi Pengguna Kasual per Hari")
fig1, ax1 = plt.subplots()
ax1.pie(casual_by_day["Jumlah Casual Users"], labels=casual_by_day.index, autopct='%1.1f%%', startangle=140, colors=plt.cm.Paired.colors)
ax1.set_title("Distribusi Pengguna Kasual Berdasarkan Hari")
st.pyplot(fig1)

# Bar Chart
st.subheader("Jumlah Pengguna Kasual per Jam")
fig2, ax2 = plt.subplots(figsize=(10, 5))
ax2.bar(casual_by_hour.index, casual_by_hour["Jumlah Casual Users"], color='lightcoral')
ax2.set_xlabel("Jam")
ax2.set_ylabel("Jumlah Pengguna Kasual")
ax2.set_title("Jumlah Pengguna Kasual Berdasarkan Jam dalam Sehari")
ax2.set_xticks(range(0, 24))
ax2.grid(axis='y', linestyle='--', alpha=0.7)
st.pyplot(fig2)

st.write("Sumber data: Dataset pengguna sepeda")